#!/usr/bin/env python3
"""Build a release artifact for the current OS (unsigned).

Pipeline:
  1. Build the Next.js static export with VRL_YOLO_GUI_BUILD=desktop.
  2. PyInstaller-package the desktop entry (`src-pyloid/main.py`) into a
     single binary (Windows) or .app folder bundle (macOS), bundling the
     static export and the 8 starter model weights.

Artifacts land in `dist/`:
  - macOS   : dist/VRL YOLO GUI.app  (+ optional .dmg if `create-dmg` is on PATH)
  - Windows : dist/VRL YOLO GUI.exe
  - Linux   : dist/VRL YOLO GUI

Note: no code signing. macOS users will need to right-click → Open the
first time, or run `xattr -dr com.apple.quarantine` on the .app.

Usage:
    python scripts/build-release.py
    python scripts/build-release.py --clean         # wipe dist/ + build/ first
    python scripts/build-release.py --skip-frontend # reuse existing apps/web/out
    python scripts/build-release.py --no-onefile    # produce a folder, not a single binary
"""

from __future__ import annotations

import argparse
import os
import platform
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _common import (  # noqa: E402
    ROOT,
    banner,
    build_static_export,
    detect_os,
    ensure_node_deps,
    ensure_python_deps,
    err,
    has_static_export,
    info,
    uv_run,
    warn,
    wipe_build_artifacts,
)

# User-facing display name — Finder bundle ("VRL YOLO GUI.app"), Windows
# executable, DMG volname, etc. Filesystem identifiers used for storage
# paths and the Pyloid single-instance lock stay hyphenated (VRL-YOLO-GUI)
# — see CLAUDE.md §11 for the split.
APP_NAME = "VRL YOLO GUI"
BUNDLE_ID = "com.atultiwari.vrl-yolo-gui"
DIST_DIR = ROOT / "dist"
BUILD_DIR = ROOT / "build"


def read_project_version() -> str:
    pyproject = (ROOT / "pyproject.toml").read_text()
    match = re.search(
        r'^\s*\[project\][^\[]*?\n\s*version\s*=\s*"([^"]+)"',
        pyproject,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        return "0.0.0"
    return match.group(1)


def version_tuple(version: str) -> tuple[int, int, int, int]:
    parts: list[int] = []
    for component in version.split("."):
        try:
            parts.append(int(re.sub(r"\D.*$", "", component)))
        except ValueError:
            parts.append(0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def write_windows_version_file(version: str, dest: Path) -> None:
    v = version_tuple(version)
    content = f"""# Auto-generated by scripts/build-release.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v},
    prodvers={v},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'Atul Tiwari'),
           StringStruct(u'FileDescription', u'{APP_NAME}'),
           StringStruct(u'FileVersion', u'{version}'),
           StringStruct(u'InternalName', u'{APP_NAME}'),
           StringStruct(u'OriginalFilename', u'{APP_NAME}.exe'),
           StringStruct(u'ProductName', u'{APP_NAME}'),
           StringStruct(u'ProductVersion', u'{version}')])
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    dest.write_text(content, encoding="utf-8")


def set_macos_bundle_version(app_path: Path, version: str) -> None:
    """Stamp the `.app`'s Info.plist with the real version.

    Must run BEFORE the inside-out re-sign so the new Info.plist hash
    lands in `_CodeSignature/CodeResources`; otherwise the signature is
    invalid.
    """
    info_plist = app_path / "Contents" / "Info.plist"
    if not info_plist.is_file():
        warn(f"  Info.plist missing at {info_plist}, skipping version stamp")
        return
    for key in ("CFBundleVersion", "CFBundleShortVersionString"):
        result = subprocess.run(
            ["/usr/bin/plutil", "-replace", key, "-string", version, str(info_plist)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            warn(f"  plutil -replace {key} failed: {result.stderr.strip()}")
    info(f"  CFBundleVersion = CFBundleShortVersionString = {version}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build an unsigned release for the current OS")
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Wipe dist/, build/, and the stale top-level *.spec before building.",
    )
    parser.add_argument(
        "--clean-build",
        action="store_true",
        help=(
            "Stronger than --clean: also wipes apps/web/.next and apps/web/out "
            "so the frontend static export is rebuilt from a cold cache. "
            "Use this before tagging a release."
        ),
    )
    parser.add_argument(
        "--skip-frontend",
        action="store_true",
        help="Use the existing apps/web/out instead of rebuilding it.",
    )
    parser.add_argument(
        "--onefile",
        action="store_true",
        help="Force PyInstaller into single-binary mode.",
    )
    parser.add_argument(
        "--no-onefile",
        action="store_true",
        help="Force PyInstaller into folder-bundle mode regardless of OS.",
    )
    parser.add_argument(
        "--arch-suffix",
        action="store_true",
        help="Rename the artifact to include the CPU arch (arm64 / x64 / x86).",
    )
    return parser.parse_args()


def _arch_suffix() -> str:
    machine = platform.machine().lower()
    if machine in {"arm64", "aarch64"}:
        return "arm64"
    if machine in {"x86_64", "amd64"}:
        return "x64"
    if machine in {"x86", "i386", "i686"}:
        return "x86"
    return machine or "unknown"


def rename_with_arch(artifact: Path, os_name: str, onefile: bool) -> Path:
    if os_name == "macos":
        return artifact

    suffix = _arch_suffix()

    folder_bundle = (
        (os_name == "windows" and not onefile)
        or (os_name == "linux" and not onefile)
    )

    if folder_bundle:
        folder = artifact.parent
        new_folder = folder.with_name(f"{folder.name}-{suffix}")
        if new_folder.exists():
            shutil.rmtree(new_folder)
        folder.rename(new_folder)
        return new_folder / artifact.name

    if os_name == "windows":
        new = artifact.with_name(f"{artifact.stem}-{suffix}.exe")
    else:
        new = artifact.with_name(f"{artifact.name}-{suffix}")

    if new.exists():
        if new.is_dir():
            shutil.rmtree(new)
        else:
            new.unlink()
    artifact.rename(new)
    return new


def _decide_onefile(args: argparse.Namespace, os_name: str) -> bool:
    if args.onefile and args.no_onefile:
        raise SystemExit("error: --onefile and --no-onefile are mutually exclusive")
    if args.onefile:
        return True
    if args.no_onefile:
        return False
    # Folder bundle on macOS (avoids the bounce-and-die one-file extractor
    # symptom under Gatekeeper), single binary on Windows + Linux.
    return os_name != "macos"


def clean() -> None:
    for target in (DIST_DIR, BUILD_DIR):
        if target.exists():
            info(f"removing {target.relative_to(ROOT)}/")
            shutil.rmtree(target)
    spec = ROOT / f"{APP_NAME}.spec"
    if spec.exists():
        spec.unlink()


def pyinstaller_args(*, onefile: bool, os_name: str) -> list[str]:
    sep = ";" if os_name == "windows" else ":"
    static_src = ROOT / "apps" / "web" / "out"
    models_src = ROOT / "models"
    splash_src = ROOT / "src-pyloid" / "splash.png"
    icon = ROOT / "src-pyloid" / "icons" / {
        "macos": "icon.icns",
        "windows": "icon.ico",
        "linux": "icon.png",
    }[os_name]

    # Qt addons that PyInstaller's --collect-all PySide6 would otherwise pull
    # in. An embedded-WebEngine app + Ultralytics workload has no use for any
    # of these — excluding them drops roughly 400 MB of Qt frameworks.
    qt_excludes = [
        "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DRender",
        "PySide6.Qt3DExtras", "PySide6.Qt3DInput", "PySide6.Qt3DLogic",
        "PySide6.QtQuick3D",
        "PySide6.QtCharts", "PySide6.QtDataVisualization",
        "PySide6.QtGraphs", "PySide6.QtGraphsWidgets",
        "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
        "PySide6.QtSpatialAudio", "PySide6.QtTextToSpeech",
        "PySide6.QtBluetooth", "PySide6.QtNfc",
        "PySide6.QtSerialBus", "PySide6.QtSerialPort",
        "PySide6.QtSensors",
        "PySide6.QtPdf", "PySide6.QtPdfWidgets",
        "PySide6.QtScxml", "PySide6.QtStateMachine",
        "PySide6.QtRemoteObjects", "PySide6.QtHttpServer",
        "PySide6.QtLocation",
        "PySide6.QtDesigner", "PySide6.QtUiTools",
        "PySide6.QtTest", "PySide6.QtHelp",
        "PySide6.QtAsyncio",
    ]

    args = [
        "pyinstaller",
        "--name", APP_NAME,
        "--windowed",
        "--clean",
        "--noconfirm",
        "--add-data", f"{static_src}{sep}apps/web/out",
        # uv installs vrl_yolo as editable via a .pth pointing at ROOT/server.
        # PyInstaller's static analyzer otherwise misses submodules; enumerate
        # them all so the bundle is exhaustive.
        "--collect-submodules", "vrl_yolo",
        "--paths", str(ROOT / "server"),
        # Force-collect everything from packages whose auto-detection is
        # known-flaky inside .app launches.
        "--collect-all", "pyloid",
        "--collect-all", "PySide6",
        # Ultralytics + torch — their hooks are partial and they ship YAML
        # configs / cached weights that PyInstaller's import walker misses.
        "--collect-all", "ultralytics",
        "--collect-all", "torch",
        "--collect-all", "torchvision",
        # Backend deps PyInstaller's static analysis sometimes misses:
        "--collect-submodules", "uvicorn",
        "--collect-submodules", "skimage",
    ]
    for mod in qt_excludes:
        args += ["--exclude-module", mod]
    if models_src.is_dir() and any(models_src.rglob("*.pt")):
        args += ["--add-data", f"{models_src}{sep}models"]
    if splash_src.is_file():
        if os_name in ("windows", "linux"):
            args += ["--splash", str(splash_src)]
        args += ["--add-data", f"{splash_src}{sep}."]
    if icon.is_file():
        args += ["--icon", str(icon)]
    if os_name == "windows":
        version_file = BUILD_DIR / "version_info.txt"
        BUILD_DIR.mkdir(parents=True, exist_ok=True)
        write_windows_version_file(read_project_version(), version_file)
        args += ["--version-file", str(version_file)]
    if onefile:
        args.append("--onefile")
    if os_name == "macos":
        args += ["--osx-bundle-identifier", BUNDLE_ID]
        args += ["--codesign-identity", "-"]

    args.append(str(ROOT / "src-pyloid" / "main.py"))
    return args


def find_artifact(os_name: str, onefile: bool) -> Path | None:
    if os_name == "macos":
        cand = DIST_DIR / f"{APP_NAME}.app"
        return cand if cand.exists() else None
    if os_name == "windows":
        if onefile:
            cand = DIST_DIR / f"{APP_NAME}.exe"
        else:
            cand = DIST_DIR / APP_NAME / f"{APP_NAME}.exe"
        return cand if cand.exists() else None
    if onefile:
        cand = DIST_DIR / APP_NAME
    else:
        cand = DIST_DIR / APP_NAME / APP_NAME
    return cand if cand.exists() else None


_MACHO_MAGIC = (
    b"\xcf\xfa\xed\xfe",
    b"\xce\xfa\xed\xfe",
    b"\xfe\xed\xfa\xce",
    b"\xfe\xed\xfa\xcf",
    b"\xca\xfe\xba\xbe",
)


def _is_macho(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    if path.suffix.lower() in (".dylib", ".so"):
        return True
    try:
        with open(path, "rb") as fp:
            return fp.read(4) in _MACHO_MAGIC
    except OSError:
        return False


_DEVTOOL_BUNDLE_STEMS: frozenset[str] = frozenset({
    "Assistant",
    "Designer",
    "Linguist",
    "qtdiag",
    "pyside6-deploy",
    "pyside6-genpyi",
    "pyside6-android-deploy",
    "pyside6-metaobjectdump",
    "pyside6-project",
    "pyside6-qml",
    "pyside6-qmlcachegen",
    "pyside6-qmlformat",
    "pyside6-qmllint",
    "pyside6-qmlls",
    "pyside6-qmltyperegistrar",
    "pyside6-qtpy2cpp",
    "pyside6-rcc",
    "pyside6-uic",
})


def _bundle_stem(entry: Path) -> str | None:
    name = entry.name
    if name.endswith("__dot__app"):
        return name[: -len("__dot__app")]
    if name.endswith(".app"):
        return name[: -len(".app")]
    return None


def _inside_framework_helpers(entry: Path, app_path: Path) -> bool:
    try:
        rel = entry.relative_to(app_path).parts
    except ValueError:
        return False
    for i, part in enumerate(rel[:-1]):
        if part.endswith(".framework") and i + 1 < len(rel) - 1 and rel[i + 1] == "Helpers":
            return True
    return False


def strip_nested_macos_bundles(app_path: Path) -> int:
    """Delete nested Qt/PySide6 developer-tool subtrees inside the bundle.

    CRITICAL: this must NOT touch `QtWebEngineProcess.app`, which lives at
    `Frameworks/PySide6/Qt/lib/QtWebEngineCore.framework/Helpers/
    QtWebEngineProcess.app`. Qt WebEngine spawns it at runtime to host the
    Chromium renderer that Pyloid uses for the webview.
    """
    removed = 0
    for entry in list(app_path.rglob("*")):
        if entry == app_path:
            continue
        if not entry.is_dir():
            continue
        stem = _bundle_stem(entry)
        if stem is None:
            continue
        if stem not in _DEVTOOL_BUNDLE_STEMS:
            continue
        if _inside_framework_helpers(entry, app_path):
            continue
        try:
            shutil.rmtree(entry)
            removed += 1
        except OSError as exc:
            warn(f"  could not remove {entry.relative_to(app_path)}: {exc}")
    return removed


def resign_macos_bundle(app_path: Path) -> bool:
    """Strip + re-apply ad-hoc signature on every Mach-O, then the .app itself.

    Required because PyInstaller's `--codesign-identity -` sometimes preserves
    the original Apple signature on bundled dylibs (notably uv-fetched
    `libpython3.11.dylib`). The dyld loader then refuses to load them at
    runtime because their Team ID doesn't match our ad-hoc-signed main binary.
    """
    info(f"Re-signing {app_path.name} inside-out (Team-ID fix)…")
    contents = app_path / "Contents"
    machos = [p for p in contents.rglob("*") if _is_macho(p)]
    info(f"  found {len(machos)} Mach-O files")

    failed = 0
    for f in machos:
        subprocess.run(
            ["codesign", "--remove-signature", str(f)],
            capture_output=True,
        )
        result = subprocess.run(
            ["codesign", "--force", "--sign", "-", str(f)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            failed += 1

    if failed:
        warn(f"  {failed} files could not be re-signed (likely non-fatal)")

    result = subprocess.run(
        ["codesign", "--force", "--sign", "-", str(app_path)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        err(f"codesign on .app failed: {result.stderr.strip()}")
        return False

    verify = subprocess.run(
        ["codesign", "--verify", "--verbose=1", str(app_path)],
        capture_output=True,
        text=True,
    )
    output = (verify.stderr + verify.stdout).strip()
    if "valid on disk" in output or verify.returncode == 0:
        info(f"  codesign --verify: ✓ {output}")
        return True
    warn(f"  codesign --verify: {output}")
    return False


def maybe_macos_dmg(app_path: Path, arch_suffix: str = "") -> Path | None:
    if not shutil.which("create-dmg"):
        info("(install `create-dmg` via brew to also produce a .dmg)")
        return None
    dmg_path = DIST_DIR / f"{app_path.stem}{arch_suffix}.dmg"
    if dmg_path.exists():
        dmg_path.unlink()
    info("Building .dmg with create-dmg…")
    result = subprocess.run(
        [
            "create-dmg",
            "--volname", app_path.stem,
            "--window-size", "540", "380",
            "--icon-size", "100",
            "--app-drop-link", "400", "190",
            "--icon", app_path.name, "140", "190",
            str(dmg_path),
            str(app_path),
        ],
        cwd=str(DIST_DIR),
    )
    if result.returncode != 0:
        warn("create-dmg failed; .app is still usable")
        return None
    return dmg_path


def main() -> int:
    args = parse_args()
    os_name = detect_os()
    banner(f"Building unsigned release for {os_name}")

    ensure_python_deps(desktop=True, ml=True)
    ensure_node_deps()

    if args.clean or args.clean_build:
        clean()
    if args.clean_build:
        banner("Cleaning frontend build cache")
        wipe_build_artifacts(web=True)

    # --skip-frontend is moot if we just nuked apps/web/out; force a rebuild.
    if args.clean_build or not args.skip_frontend or not has_static_export():
        build_static_export()
    else:
        info("Reusing existing apps/web/out/")

    DIST_DIR.mkdir(exist_ok=True)
    BUILD_DIR.mkdir(exist_ok=True)

    banner("Running PyInstaller")
    onefile = _decide_onefile(args, os_name)
    info(f"PyInstaller mode: {'single-file binary' if onefile else 'folder bundle'}")
    cmd = [*uv_run(), *pyinstaller_args(onefile=onefile, os_name=os_name)]
    info(" ".join(cmd))
    result = subprocess.run(cmd, cwd=str(ROOT), env=os.environ.copy())
    if result.returncode != 0:
        err("PyInstaller failed")
        return result.returncode

    artifact = find_artifact(os_name, onefile)
    if artifact is None:
        warn("PyInstaller succeeded but artifact not found in expected location")
        return 0

    if os_name == "macos" and artifact.suffix == ".app":
        banner("Post-build cleanup (Qt developer tools — preserves QtWebEngineProcess)")
        n = strip_nested_macos_bundles(artifact)
        info(f"  removed {n} Qt devtool bundle(s)")
        banner("Stamping bundle version into Info.plist")
        set_macos_bundle_version(artifact, read_project_version())
        banner("Post-build re-sign (macOS Team-ID fix)")
        resign_macos_bundle(artifact)

    arch_suffix = f"-{_arch_suffix()}" if args.arch_suffix else ""

    if args.arch_suffix:
        banner(f"Arch suffix: {arch_suffix}")
        artifact = rename_with_arch(artifact, os_name, onefile)
        if os_name == "macos":
            info(f"  .app stays bare: {artifact.name}")
            info(f"  arch will be added to the .dmg name: {arch_suffix}")
        else:
            info(f"  -> {artifact}")

    banner("Release built")
    info(f"Artifact: {artifact}")
    if os_name == "macos":
        info("Unsigned .app — to launch: right-click → Open, OR run:")
        info(f"  xattr -dr com.apple.quarantine '{artifact}'")
        maybe_macos_dmg(artifact, arch_suffix)
    elif os_name == "windows":
        info("Unsigned .exe — Windows SmartScreen may warn on first launch.")
    else:
        info("Unsigned Linux binary — make it executable if needed: chmod +x")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
